; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

projects[admin_menu][version] = "3.x-dev"

projects[apachesolr][version] = "1.7"

projects[auto_nodetitle][version] = "1.0"

projects[backup_migrate][version] = "3.1"

projects[coder][version] = "2.5"

projects[better_formats][version] = "1.x"

projects[boxes][version] = "1.2"

projects[ctools][version] = "1.9"

projects[content_taxonomy][version] = "1.x"

projects[context][version] = "3.6"

projects[date][version] = "2.9"

projects[devel][version] = "1.5"

projects[dfp][version] = "1.4"

projects[diff][version] = "3.2"

projects[ds][version] = "2.11"

projects[elysia_cron][version] = "2.1"

projects[entity][version] = "1.6"

projects[entity_autocomplete][version] = "1.x"

projects[entityreference][version] = "1.1"

projects[features_extra][version] = "1.0"

projects[features][version] = "2.7"

projects[google_analytics][version] = "2.1"

projects[i18n][version] = "1.13"

projects[imagecrop][version] = "1.x"

projects[imce][version] = "1.x-dev"

projects[imce_wysiwyg][version] = "1.x"

projects[jquery_update][version] = "2.7"

projects[libraries][version] = "2.x"

projects[link][version] = "1.3"

projects[memcache][version] = "1.5"

projects[metatag][version] = "1.7"

projects[mobile_detect][version] = "1.x"

projects[module_filter][version] = "2.0"

projects[references][version] = "2.1"

projects[nodeblock][version] = "1.6"

projects[nodequeue][version] = "2.0"

projects[pathauto][version] = "1.3"

projects[pollanon][version] = "1.1"

projects[redirect][version] = "1.x"

projects[schemaorg][version] = "1.x"

projects[strongarm][version] = "2.0"

projects[taxonomy_access_fix][version] = "2.2"

projects[taxonomy_manager][version] = "1.0"

projects[term_merge][version] = "1.2"

projects[token][version] = "1.6"

projects[transliteration][version] = "3.2"

projects[variable][version] = "2.5"

projects[varnish][version] = "1.x"

projects[video_embed_field][version] = "2.x"

projects[views][version] = "3.12"

projects[views_arguments_extras][version] = "1.x"

projects[views_boxes][version] = "1.0"

projects[vntf][version] = "1.x"

projects[wysiwyg][version] = "2.x-dev"

projects[xmlsitemap][version] = "2.2"

projects[entitycache][version] = "1.x"

projects[htmlpurifier][version] = "2.x"

; Themes
projects[adaptivetheme][version] = "3.2"

projects[business_enterprises][version] = "1.1"

projects[rubik][version] = "4.1"

projects[simpleclean][version] = "1.4"

projects[tao][version] = "3.1"

projects[virgo_zymphonies_theme][version] = "1.0"

projects[panels][version] = "3.x"

projects[formblock][version] = "1.x-dev"

projects[fast_404][version] = "1.x-dev"

projects[advagg][version] = "2.x"

projects[field_slideshow][version] = "1.x"

projects[themekey][version] = "3.x"

projects[context_error] = "1.x"

projects[services] = "3.x"
projects[oauth2_server] = "1.x"
projects[xautoload] = "5.x"

libraries[oauth2-server-php][download][type] = "get"
libraries[oauth2-server-php][download][url] = "https://github.com/bshaffer/oauth2-server-php/archive/v1.8.0.tar.gz"
